# Generated by Django 3.0.6 on 2020-06-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moje_konto',
            options={'verbose_name': 'Moje_Konto', 'verbose_name_plural': 'Konta'},
        ),
    ]
