# Generated by Django 3.0.6 on 2020-06-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grzyb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to=grzyb.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='data publickacji')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='opis')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grzyb.BlogPost')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
