# Generated by Django 3.0.6 on 2020-06-11 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grzyb.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grzyb', '0004_auto_20200611_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(max_length=5000, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to=grzyb.models.upload_location, verbose_name='obrazek'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktywne'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='stworzone'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='Comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzyb.Comment', verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='Moje_Konto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Moje_Konto'),
        ),
        migrations.AlterField(
            model_name='like',
            name='Comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzyb.Comment', verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='like',
            name='Moje_Konto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Moje Konto'),
        ),
        migrations.CreateModel(
            name='LikeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzyb.BlogPost')),
                ('Moje_Konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Moje Konto')),
            ],
        ),
        migrations.CreateModel(
            name='DislikeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grzyb.BlogPost')),
                ('Moje_Konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Moje_Konto')),
            ],
        ),
    ]
